export type Day = "Sun" | "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat";

export type TimeRange = { from: string; to: string };

export type Doctor = {
  slug: string;
  initials: string;
  name: string;
  specialty: string;
  qualifications: string;
  hospital: string;
  experience: number;
  rating: number;
  reviews: number;
  price: number;
  followUp: number;
  available: boolean;
  color: string;
  availableDays: Day[];
  schedule: Partial<Record<Day, TimeRange>>;
};

export function nameToSlug(name: string): string {
  return name.replace("Dr. ", "").toLowerCase().replace(/\s+/g, "-");
}

export const allDoctors: Doctor[] = [
  {
    slug: "rashida-alam",
    initials: "RA",
    name: "Dr. Rashida Alam",
    specialty: "Cardiologist",
    qualifications: "MBBS, MD (Cardiology), FCPS",
    hospital: "National Heart Foundation, Dhaka",
    experience: 12,
    rating: 4.9,
    reviews: 312,
    price: 800,
    followUp: 500,
    available: true,
    color: "bg-rose-500",
    availableDays: ["Mon", "Wed", "Thu", "Sat"],
    schedule: {
      Mon: { from: "10:00 AM", to: "1:00 PM" },
      Wed: { from: "3:00 PM",  to: "6:00 PM" },
      Thu: { from: "10:00 AM", to: "1:00 PM" },
      Sat: { from: "9:00 AM",  to: "12:00 PM" },
    },
  },
  {
    slug: "mehedi-hassan",
    initials: "MH",
    name: "Dr. Mehedi Hassan",
    specialty: "Neurologist",
    qualifications: "MBBS, MD (Neurology)",
    hospital: "Bangabandhu Sheikh Mujib Medical University",
    experience: 9,
    rating: 4.8,
    reviews: 198,
    price: 900,
    followUp: 600,
    available: true,
    color: "bg-sky-600",
    availableDays: ["Tue", "Wed", "Fri"],
    schedule: {
      Tue: { from: "9:00 AM",  to: "12:00 PM" },
      Wed: { from: "2:00 PM",  to: "5:00 PM" },
      Fri: { from: "10:00 AM", to: "1:00 PM" },
    },
  },
  {
    slug: "sumaiya-faruk",
    initials: "SF",
    name: "Dr. Sumaiya Faruk",
    specialty: "Dermatologist",
    qualifications: "MBBS, DDV (Dermatology)",
    hospital: "Square Hospitals Ltd., Dhaka",
    experience: 7,
    rating: 4.7,
    reviews: 245,
    price: 700,
    followUp: 450,
    available: false,
    color: "bg-violet-500",
    availableDays: ["Mon", "Tue", "Thu"],
    schedule: {
      Mon: { from: "11:00 AM", to: "2:00 PM" },
      Tue: { from: "3:00 PM",  to: "6:00 PM" },
      Thu: { from: "11:00 AM", to: "2:00 PM" },
    },
  },
  {
    slug: "kamal-rahman",
    initials: "KR",
    name: "Dr. Kamal Rahman",
    specialty: "Pediatrician",
    qualifications: "MBBS, DCH, FCPS (Paediatrics)",
    hospital: "Dhaka Shishu Hospital",
    experience: 15,
    rating: 4.9,
    reviews: 480,
    price: 600,
    followUp: 400,
    available: true,
    color: "bg-emerald-600",
    availableDays: ["Sun", "Mon", "Wed", "Fri", "Sat"],
    schedule: {
      Sun: { from: "9:00 AM",  to: "11:00 AM" },
      Mon: { from: "10:00 AM", to: "1:00 PM" },
      Wed: { from: "2:00 PM",  to: "5:00 PM" },
      Fri: { from: "9:00 AM",  to: "12:00 PM" },
      Sat: { from: "10:00 AM", to: "1:00 PM" },
    },
  },
  {
    slug: "nasrin-akter",
    initials: "NA",
    name: "Dr. Nasrin Akter",
    specialty: "Gynecologist",
    qualifications: "MBBS, MS (Gynaecology & Obstetrics)",
    hospital: "Evercare Hospital, Dhaka",
    experience: 11,
    rating: 4.8,
    reviews: 390,
    price: 850,
    followUp: 550,
    available: true,
    color: "bg-pink-500",
    availableDays: ["Mon", "Tue", "Wed", "Thu"],
    schedule: {
      Mon: { from: "9:00 AM",  to: "12:00 PM" },
      Tue: { from: "2:00 PM",  to: "5:00 PM" },
      Wed: { from: "9:00 AM",  to: "12:00 PM" },
      Thu: { from: "3:00 PM",  to: "6:00 PM" },
    },
  },
  {
    slug: "tariq-islam",
    initials: "TI",
    name: "Dr. Tariq Islam",
    specialty: "Orthopedist",
    qualifications: "MBBS, MS (Orthopaedic Surgery)",
    hospital: "Combined Military Hospital, Dhaka",
    experience: 14,
    rating: 4.7,
    reviews: 210,
    price: 1000,
    followUp: 700,
    available: false,
    color: "bg-amber-600",
    availableDays: ["Wed", "Thu", "Sat"],
    schedule: {
      Wed: { from: "10:00 AM", to: "1:00 PM" },
      Thu: { from: "3:00 PM",  to: "6:00 PM" },
      Sat: { from: "9:00 AM",  to: "12:00 PM" },
    },
  },
  {
    slug: "prodip-banik",
    initials: "PB",
    name: "Dr. Prodip Banik",
    specialty: "General Physician",
    qualifications: "MBBS, FCGP",
    hospital: "Popular Medical Centre, Dhaka",
    experience: 5,
    rating: 4.6,
    reviews: 520,
    price: 400,
    followUp: 250,
    available: true,
    color: "bg-teal-600",
    availableDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    schedule: {
      Sun: { from: "9:00 AM",  to: "11:00 AM" },
      Mon: { from: "9:00 AM",  to: "12:00 PM" },
      Tue: { from: "2:00 PM",  to: "5:00 PM" },
      Wed: { from: "9:00 AM",  to: "12:00 PM" },
      Thu: { from: "2:00 PM",  to: "5:00 PM" },
      Fri: { from: "9:00 AM",  to: "11:00 AM" },
      Sat: { from: "10:00 AM", to: "1:00 PM" },
    },
  },
  {
    slug: "zarin-hossain",
    initials: "ZH",
    name: "Dr. Zarin Hossain",
    specialty: "ENT Specialist",
    qualifications: "MBBS, MS (ENT)",
    hospital: "Birdem General Hospital, Dhaka",
    experience: 8,
    rating: 4.8,
    reviews: 176,
    price: 750,
    followUp: 500,
    available: true,
    color: "bg-indigo-500",
    availableDays: ["Mon", "Thu", "Sat"],
    schedule: {
      Mon: { from: "10:00 AM", to: "1:00 PM" },
      Thu: { from: "3:00 PM",  to: "6:00 PM" },
      Sat: { from: "9:00 AM",  to: "12:00 PM" },
    },
  },
  {
    slug: "aminul-miah",
    initials: "AM",
    name: "Dr. Aminul Miah",
    specialty: "Gastroenterologist",
    qualifications: "MBBS, MD (Gastroenterology)",
    hospital: "Ibn Sina Hospital, Dhaka",
    experience: 10,
    rating: 4.7,
    reviews: 143,
    price: 950,
    followUp: 650,
    available: true,
    color: "bg-cyan-600",
    availableDays: ["Tue", "Wed", "Fri", "Sat"],
    schedule: {
      Tue: { from: "9:00 AM",  to: "12:00 PM" },
      Wed: { from: "2:00 PM",  to: "5:00 PM" },
      Fri: { from: "10:00 AM", to: "1:00 PM" },
      Sat: { from: "3:00 PM",  to: "6:00 PM" },
    },
  },
  {
    slug: "rina-khatun",
    initials: "RK",
    name: "Dr. Rina Khatun",
    specialty: "Ophthalmologist",
    qualifications: "MBBS, DO (Ophthalmology)",
    hospital: "National Eye Care, Dhaka",
    experience: 6,
    rating: 4.5,
    reviews: 289,
    price: 700,
    followUp: 450,
    available: false,
    color: "bg-purple-500",
    availableDays: ["Sun", "Mon", "Wed"],
    schedule: {
      Sun: { from: "9:00 AM",  to: "11:00 AM" },
      Mon: { from: "11:00 AM", to: "2:00 PM" },
      Wed: { from: "3:00 PM",  to: "6:00 PM" },
    },
  },
  {
    slug: "sabbir-noor",
    initials: "SN",
    name: "Dr. Sabbir Noor",
    specialty: "Psychiatrist",
    qualifications: "MBBS, MD (Psychiatry)",
    hospital: "National Institute of Mental Health, Dhaka",
    experience: 9,
    rating: 4.6,
    reviews: 95,
    price: 1200,
    followUp: 800,
    available: true,
    color: "bg-slate-600",
    availableDays: ["Mon", "Thu", "Fri"],
    schedule: {
      Mon: { from: "10:00 AM", to: "1:00 PM" },
      Thu: { from: "2:00 PM",  to: "5:00 PM" },
      Fri: { from: "10:00 AM", to: "12:00 PM" },
    },
  },
  {
    slug: "farzana-ahmed",
    initials: "FA",
    name: "Dr. Farzana Ahmed",
    specialty: "Endocrinologist",
    qualifications: "MBBS, MD (Endocrinology & Metabolism)",
    hospital: "BIRDEM General Hospital, Dhaka",
    experience: 13,
    rating: 4.9,
    reviews: 267,
    price: 900,
    followUp: 600,
    available: true,
    color: "bg-orange-500",
    availableDays: ["Tue", "Wed", "Thu", "Sat"],
    schedule: {
      Tue: { from: "9:00 AM",  to: "12:00 PM" },
      Wed: { from: "2:00 PM",  to: "5:00 PM" },
      Thu: { from: "10:00 AM", to: "1:00 PM" },
      Sat: { from: "9:00 AM",  to: "11:00 AM" },
    },
  },
];
