export type MedicineForm = "Tablet" | "Capsule" | "Syrup" | "Injection" | "Cream" | "Drops";

export type Medicine = {
  slug: string;
  name: string;
  genericName: string;
  brand: string;
  manufacturer: string;
  form: MedicineForm;
  strength: string;
  packSize: string;
  price: number;
  prescriptionRequired: boolean;
  category: string;
  color: string;
  badge: "Popular" | "Rx" | "OTC" | null;
  inStock: boolean;
  description: string;
  uses: string[];
  dosage: string;
  frequency: string;
  duration: string;
  sideEffects: string[];
  warnings: string[];
  contraindications: string[];
  storage: string;
  relatedSlugs: string[];
};

export const allMedicines: Medicine[] = [
  {
    slug: "paracetamol-500mg",
    name: "Paracetamol 500mg",
    genericName: "Paracetamol (Acetaminophen)",
    brand: "Napa",
    manufacturer: "Beximco Pharmaceuticals Ltd.",
    form: "Tablet",
    strength: "500 mg",
    packSize: "10 tablets / strip",
    price: 8,
    prescriptionRequired: false,
    category: "Analgesic & Antipyretic",
    color: "bg-sky-100 text-sky-700",
    badge: "Popular",
    inStock: true,
    description:
      "Paracetamol is a commonly used medicine for pain relief and to reduce fever. It can be used to treat headaches, muscle aches, arthritis, backaches, toothaches, colds, and fevers.",
    uses: [
      "Relief of mild to moderate pain",
      "Reduction of fever",
      "Headache and migraine",
      "Cold and flu symptoms",
      "Post-vaccination fever",
    ],
    dosage: "500 mg – 1000 mg per dose",
    frequency: "Every 4–6 hours as needed",
    duration: "Do not use for more than 10 days for pain or 3 days for fever",
    sideEffects: [
      "Nausea (rare)",
      "Allergic skin reactions (rare)",
      "Liver damage with overdose",
    ],
    warnings: [
      "Do not exceed 4 g (4000 mg) per day",
      "Avoid alcohol while taking this medicine",
      "Consult a doctor if symptoms persist beyond 3 days",
    ],
    contraindications: [
      "Severe liver disease",
      "Hypersensitivity to paracetamol",
    ],
    storage: "Store below 30°C, away from light and moisture.",
    relatedSlugs: ["ibuprofen-400mg", "cetirizine-10mg", "antacid-suspension"],
  },
  {
    slug: "amoxicillin-500mg",
    name: "Amoxicillin 500mg",
    genericName: "Amoxicillin Trihydrate",
    brand: "Moxacil",
    manufacturer: "ACI Limited",
    form: "Capsule",
    strength: "500 mg",
    packSize: "12 capsules / box",
    price: 72,
    prescriptionRequired: true,
    category: "Antibiotic",
    color: "bg-amber-100 text-amber-700",
    badge: "Rx",
    inStock: true,
    description:
      "Amoxicillin is a penicillin antibiotic used to treat many different types of infections caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.",
    uses: [
      "Respiratory tract infections",
      "Ear, nose and throat infections",
      "Urinary tract infections",
      "Skin and soft tissue infections",
      "Dental infections",
    ],
    dosage: "500 mg per dose",
    frequency: "3 times daily (every 8 hours)",
    duration: "Complete the full 5–7 day course as prescribed",
    sideEffects: [
      "Diarrhoea",
      "Nausea and vomiting",
      "Skin rash",
      "Allergic reactions (rare)",
    ],
    warnings: [
      "Always complete the full antibiotic course",
      "Inform your doctor about penicillin allergy",
      "May reduce effectiveness of oral contraceptives",
    ],
    contraindications: [
      "Penicillin or beta-lactam allergy",
      "Mononucleosis (glandular fever)",
    ],
    storage: "Store below 25°C in a dry place.",
    relatedSlugs: ["metronidazole-400mg", "omeprazole-20mg"],
  },
  {
    slug: "metformin-500mg",
    name: "Metformin 500mg",
    genericName: "Metformin Hydrochloride",
    brand: "Glucophage",
    manufacturer: "Opsonin Pharma Ltd.",
    form: "Tablet",
    strength: "500 mg",
    packSize: "30 tablets / box",
    price: 75,
    prescriptionRequired: true,
    category: "Antidiabetic",
    color: "bg-emerald-100 text-emerald-700",
    badge: "Rx",
    inStock: true,
    description:
      "Metformin is used to treat type 2 diabetes. It helps control blood sugar levels by decreasing glucose production in the liver and improving insulin sensitivity.",
    uses: [
      "Type 2 diabetes management",
      "Polycystic ovary syndrome (PCOS)",
      "Prevention of type 2 diabetes in high-risk patients",
    ],
    dosage: "500 mg per dose",
    frequency: "2–3 times daily with meals",
    duration: "Long-term use as directed by a doctor",
    sideEffects: [
      "Nausea and stomach upset (especially initially)",
      "Diarrhoea",
      "Metallic taste",
      "Lactic acidosis (rare, serious)",
    ],
    warnings: [
      "Take with food to reduce stomach upset",
      "Stop before surgery or contrast imaging procedures",
      "Monitor kidney function regularly",
    ],
    contraindications: [
      "Severe kidney disease (eGFR < 30)",
      "Liver disease",
      "Excessive alcohol consumption",
    ],
    storage: "Store below 30°C away from moisture.",
    relatedSlugs: ["paracetamol-500mg", "amlodipine-5mg"],
  },
  {
    slug: "amlodipine-5mg",
    name: "Amlodipine 5mg",
    genericName: "Amlodipine Besylate",
    brand: "Amdocal",
    manufacturer: "Renata Limited",
    form: "Tablet",
    strength: "5 mg",
    packSize: "30 tablets / box",
    price: 110,
    prescriptionRequired: true,
    category: "Antihypertensive / Calcium Channel Blocker",
    color: "bg-rose-100 text-rose-700",
    badge: "Rx",
    inStock: true,
    description:
      "Amlodipine is a calcium channel blocker used to treat high blood pressure and chest pain (angina). It relaxes blood vessels so the heart does not have to work as hard.",
    uses: [
      "Hypertension (high blood pressure)",
      "Stable and vasospastic angina",
      "Coronary artery disease",
    ],
    dosage: "5 mg once daily (may increase to 10 mg)",
    frequency: "Once daily",
    duration: "Long-term as directed by a cardiologist",
    sideEffects: [
      "Ankle swelling (oedema)",
      "Flushing",
      "Headache",
      "Dizziness",
      "Palpitations",
    ],
    warnings: [
      "Do not stop abruptly — taper under medical supervision",
      "May cause dizziness; avoid driving initially",
      "Inform doctor of all other medications",
    ],
    contraindications: [
      "Cardiogenic shock",
      "Severe aortic stenosis",
      "Hypersensitivity to dihydropyridines",
    ],
    storage: "Store below 30°C protected from light.",
    relatedSlugs: ["metformin-500mg", "omeprazole-20mg"],
  },
  {
    slug: "omeprazole-20mg",
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    brand: "Losectil",
    manufacturer: "Eskayef Bangladesh Ltd.",
    form: "Capsule",
    strength: "20 mg",
    packSize: "14 capsules / box",
    price: 95,
    prescriptionRequired: false,
    category: "Proton Pump Inhibitor (PPI)",
    color: "bg-purple-100 text-purple-700",
    badge: "OTC",
    inStock: true,
    description:
      "Omeprazole reduces the amount of acid produced in the stomach. It is used to treat conditions caused by excess acid such as heartburn, GERD, and stomach ulcers.",
    uses: [
      "Gastroesophageal reflux disease (GERD)",
      "Stomach and duodenal ulcers",
      "Heartburn and acid indigestion",
      "H. pylori eradication (with antibiotics)",
      "Zollinger-Ellison syndrome",
    ],
    dosage: "20 mg per dose",
    frequency: "Once daily before a meal",
    duration: "2–8 weeks typically; long-term under doctor supervision",
    sideEffects: [
      "Headache",
      "Diarrhoea or constipation",
      "Nausea",
      "Stomach pain",
      "Low magnesium with long-term use",
    ],
    warnings: [
      "Take 30 minutes before meals for best effect",
      "Long-term use may reduce vitamin B12 absorption",
      "Do not crush delayed-release capsules",
    ],
    contraindications: [
      "Hypersensitivity to omeprazole or benzimidazoles",
    ],
    storage: "Store below 30°C in a dry place.",
    relatedSlugs: ["amoxicillin-500mg", "metronidazole-400mg", "antacid-suspension"],
  },
  {
    slug: "cetirizine-10mg",
    name: "Cetirizine 10mg",
    genericName: "Cetirizine Dihydrochloride",
    brand: "Cetrizin",
    manufacturer: "Drug International Ltd.",
    form: "Tablet",
    strength: "10 mg",
    packSize: "10 tablets / strip",
    price: 60,
    prescriptionRequired: false,
    category: "Antihistamine",
    color: "bg-indigo-100 text-indigo-700",
    badge: "OTC",
    inStock: true,
    description:
      "Cetirizine is an antihistamine used to relieve allergy symptoms such as runny nose, watery eyes, itching, and sneezing. It also reduces itching due to hives.",
    uses: [
      "Allergic rhinitis (hay fever)",
      "Chronic urticaria (hives)",
      "Allergic conjunctivitis",
      "Itchy skin conditions",
    ],
    dosage: "10 mg per dose",
    frequency: "Once daily (evening preferred)",
    duration: "As needed or as directed",
    sideEffects: [
      "Drowsiness (less than older antihistamines)",
      "Dry mouth",
      "Headache",
      "Fatigue",
    ],
    warnings: [
      "May cause drowsiness — use caution when driving",
      "Avoid alcohol",
      "Use with caution in kidney impairment",
    ],
    contraindications: [
      "Hypersensitivity to cetirizine or hydroxyzine",
      "Severe renal impairment",
    ],
    storage: "Store below 30°C away from moisture.",
    relatedSlugs: ["paracetamol-500mg", "vitamin-c-500mg"],
  },
  {
    slug: "vitamin-c-500mg",
    name: "Vitamin C 500mg",
    genericName: "Ascorbic Acid",
    brand: "VitaC",
    manufacturer: "Beximco Pharmaceuticals Ltd.",
    form: "Tablet",
    strength: "500 mg",
    packSize: "30 tablets / bottle",
    price: 120,
    prescriptionRequired: false,
    category: "Vitamin & Supplement",
    color: "bg-orange-100 text-orange-700",
    badge: "Popular",
    inStock: true,
    description:
      "Vitamin C (ascorbic acid) is an essential nutrient and antioxidant. It supports the immune system, aids in collagen synthesis, and helps the body absorb iron.",
    uses: [
      "Vitamin C deficiency (scurvy prevention)",
      "Immune system support",
      "Antioxidant protection",
      "Improved iron absorption",
      "Wound healing support",
    ],
    dosage: "500 mg per dose",
    frequency: "Once or twice daily",
    duration: "Daily supplementation as needed",
    sideEffects: [
      "Nausea with high doses",
      "Diarrhoea with high doses",
      "Kidney stones with very high doses (rare)",
    ],
    warnings: [
      "Do not exceed 2000 mg per day",
      "Consult a doctor if you have a history of kidney stones",
    ],
    contraindications: ["Hyperoxaluria"],
    storage: "Store in a cool, dry place below 25°C.",
    relatedSlugs: ["cetirizine-10mg", "paracetamol-500mg"],
  },
  {
    slug: "antacid-suspension",
    name: "Antacid Suspension",
    genericName: "Aluminium Hydroxide + Magnesium Hydroxide",
    brand: "Antadine",
    manufacturer: "ACI Limited",
    form: "Syrup",
    strength: "200 mg/5 ml + 200 mg/5 ml",
    packSize: "200 ml bottle",
    price: 80,
    prescriptionRequired: false,
    category: "Antacid",
    color: "bg-teal-100 text-teal-700",
    badge: "OTC",
    inStock: true,
    description:
      "Antacid suspension neutralises excess stomach acid to relieve heartburn, indigestion, acid reflux, and stomach discomfort. Works quickly on contact.",
    uses: [
      "Heartburn and acid indigestion",
      "Stomach upset and bloating",
      "Acid reflux symptoms",
      "Peptic ulcer pain relief",
    ],
    dosage: "10–20 ml (2–4 teaspoons)",
    frequency: "3–4 times daily, after meals and at bedtime",
    duration: "Short-term; see a doctor if symptoms persist beyond 2 weeks",
    sideEffects: [
      "Constipation (aluminium hydroxide)",
      "Diarrhoea (magnesium hydroxide)",
      "Chalky taste",
    ],
    warnings: [
      "Shake well before use",
      "May reduce absorption of other medications — take 2 hours apart",
      "Use with caution in kidney disease",
    ],
    contraindications: [
      "Severe kidney failure",
      "Hypophosphataemia",
    ],
    storage: "Store below 30°C. Do not freeze.",
    relatedSlugs: ["omeprazole-20mg", "paracetamol-500mg"],
  },
  {
    slug: "ibuprofen-400mg",
    name: "Ibuprofen 400mg",
    genericName: "Ibuprofen",
    brand: "Brufen",
    manufacturer: "Abbott Laboratories",
    form: "Tablet",
    strength: "400 mg",
    packSize: "10 tablets / strip",
    price: 40,
    prescriptionRequired: false,
    category: "NSAID / Anti-inflammatory",
    color: "bg-red-100 text-red-700",
    badge: "OTC",
    inStock: true,
    description:
      "Ibuprofen is a non-steroidal anti-inflammatory drug (NSAID) used to relieve pain, reduce inflammation, and lower fever. Effective for muscle pain, dental pain, and arthritis.",
    uses: [
      "Mild to moderate pain relief",
      "Fever reduction",
      "Muscle and joint pain",
      "Dental pain",
      "Dysmenorrhoea (period pain)",
      "Arthritis and rheumatic conditions",
    ],
    dosage: "400 mg per dose",
    frequency: "3 times daily (every 6–8 hours)",
    duration: "Short-term; maximum 10 days for pain",
    sideEffects: [
      "Stomach upset, nausea",
      "Heartburn",
      "Dizziness",
      "Increased blood pressure with long-term use",
      "Risk of stomach bleeding with prolonged use",
    ],
    warnings: [
      "Always take with food or milk",
      "Avoid in peptic ulcer disease",
      "Use the lowest effective dose for the shortest time",
      "Avoid in last trimester of pregnancy",
    ],
    contraindications: [
      "Active peptic ulcer or GI bleeding",
      "Severe heart, kidney or liver failure",
      "Aspirin-sensitive asthma",
    ],
    storage: "Store below 30°C away from moisture.",
    relatedSlugs: ["paracetamol-500mg", "cetirizine-10mg"],
  },
  {
    slug: "metronidazole-400mg",
    name: "Metronidazole 400mg",
    genericName: "Metronidazole",
    brand: "Amodis",
    manufacturer: "Sanofi Bangladesh Ltd.",
    form: "Tablet",
    strength: "400 mg",
    packSize: "21 tablets / box",
    price: 55,
    prescriptionRequired: true,
    category: "Antibiotic / Antiprotozoal",
    color: "bg-cyan-100 text-cyan-700",
    badge: "Rx",
    inStock: false,
    description:
      "Metronidazole is an antibiotic used to treat bacterial and protozoal infections including anaerobic bacteria, Giardia, Entamoeba, Trichomonas, and bacterial vaginosis.",
    uses: [
      "Bacterial infections (anaerobic)",
      "Amoebic dysentery and liver abscess",
      "Giardiasis",
      "Trichomoniasis",
      "Bacterial vaginosis",
      "H. pylori eradication",
    ],
    dosage: "400 mg per dose",
    frequency: "2–3 times daily as directed",
    duration: "5–10 days depending on the infection",
    sideEffects: [
      "Nausea and metallic taste",
      "Headache",
      "Dizziness",
      "Dark urine (harmless)",
    ],
    warnings: [
      "Strictly avoid alcohol during and 48 hours after treatment",
      "Complete the full course",
      "May cause peripheral neuropathy with long-term use",
    ],
    contraindications: [
      "First trimester of pregnancy",
      "Hypersensitivity to metronidazole or nitroimidazoles",
    ],
    storage: "Store below 25°C protected from light.",
    relatedSlugs: ["amoxicillin-500mg", "omeprazole-20mg"],
  },
];
